org: dimacros
frameworkVersion: "4"
service: medical-center-service

stages:
  dev:
    name: dev
    region: us-east-1
    params:
      DATABASE_PE_CONNECTION_STRING: ${env:DATABASE_PE_CONNECTION_STRING}
      DATABASE_CL_CONNECTION_STRING: ${env:DATABASE_CL_CONNECTION_STRING}
      EVENT_BRIDGE_SOURCE_NAME: ${self:service}-${sls:stage}
      DYNAMODB_TABLE_APPOINTMENTS:
        Ref: AppointmentsTable
      SNS_TOPIC_PERUVIAN_APPOINTMENT_CREATED:
        Ref: PeruvianAppointmentTopic
      SNS_TOPIC_CHILEAN_APPOINTMENT_CREATED:
        Ref: ChileanAppointmentTopic
  prod:
    name: prod
    region: us-east-1
    params:

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs20.x
  tags:
    framework: serverless
    project: rimac-challenge
  tracing:
    lambda: true

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Scan
            - dynamodb:UpdateItem
            - dynamodb:Query
          Resource:
            - Fn::GetAtt:
                - AppointmentsTable
                - Arn
            - Fn::Join:
                - "/"
                - - Fn::GetAtt: [AppointmentsTable, Arn]
                  - "index"
                  - "*"
        - Effect: Allow
          Action:
            - sns:Publish
            - sns:Subscribe
            - sns:Receive
            - sns:ListSubscriptions
            - sns:ListSubscriptionsByTopic
          Resource:
            - Ref: PeruvianAppointmentTopic
            - Ref: ChileanAppointmentTopic
        - Effect: Allow
          Action:
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
          Resource:
            - Fn::GetAtt:
                - BookPeruvianAppointmentQueue
                - Arn
            - Fn::GetAtt:
                - BookChileanAppointmentQueue
                - Arn
        - Effect: Allow
          Action:
            - events:PutEvents
          Resource:
            - arn:aws:events:${aws:region}:${aws:accountId}:event-bus/default

functions:
  appointmentRootSchema:
    handler: src/server/getRootSchema.handler
    environment:
      DATABASE_CL_CONNECTION_STRING: ${param:DATABASE_CL_CONNECTION_STRING}
      DATABASE_PE_CONNECTION_STRING: ${param:DATABASE_PE_CONNECTION_STRING}
    events:
      - httpApi: "GET /"
  bookPeruvianAppointment:
    handler: src/server/pe/bookAppointment.handler
    environment:
      DATABASE_CL_CONNECTION_STRING: ${param:DATABASE_CL_CONNECTION_STRING}
      DATABASE_PE_CONNECTION_STRING: ${param:DATABASE_PE_CONNECTION_STRING}
      DYNAMODB_TABLE_APPOINTMENTS: ${param:DYNAMODB_TABLE_APPOINTMENTS}
      SNS_TOPIC_PERUVIAN_APPOINTMENT_CREATED: ${param:SNS_TOPIC_PERUVIAN_APPOINTMENT_CREATED}
      SNS_TOPIC_CHILEAN_APPOINTMENT_CREATED: ${param:SNS_TOPIC_CHILEAN_APPOINTMENT_CREATED}
      EVENTBRIDGE_SOURCE_APPOINTMENT_SERVICE: ${param:EVENT_BRIDGE_SOURCE_NAME}
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - BookPeruvianAppointmentQueue
              - Arn

  bookChileanAppointment:
    handler: src/server/cl/bookAppointment.handler
    environment:
      DATABASE_CL_CONNECTION_STRING: ${param:DATABASE_CL_CONNECTION_STRING}
      DATABASE_PE_CONNECTION_STRING: ${param:DATABASE_PE_CONNECTION_STRING}
      DYNAMODB_TABLE_APPOINTMENTS: ${param:DYNAMODB_TABLE_APPOINTMENTS}
      SNS_TOPIC_PERUVIAN_APPOINTMENT_CREATED: ${param:SNS_TOPIC_PERUVIAN_APPOINTMENT_CREATED}
      SNS_TOPIC_CHILEAN_APPOINTMENT_CREATED: ${param:SNS_TOPIC_CHILEAN_APPOINTMENT_CREATED}
      EVENTBRIDGE_SOURCE_APPOINTMENT_SERVICE: ${param:EVENT_BRIDGE_SOURCE_NAME}
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - BookChileanAppointmentQueue
              - Arn

  createAppointment:
    handler: src/server/createAppointment.handler
    environment:
      DYNAMODB_TABLE_APPOINTMENTS: ${param:DYNAMODB_TABLE_APPOINTMENTS}
      SNS_TOPIC_PERUVIAN_APPOINTMENT_CREATED: ${param:SNS_TOPIC_PERUVIAN_APPOINTMENT_CREATED}
      SNS_TOPIC_CHILEAN_APPOINTMENT_CREATED: ${param:SNS_TOPIC_CHILEAN_APPOINTMENT_CREATED}
    events:
      - httpApi: "POST /appointments"

  getAppointments:
    handler: src/server/getAppointments.handler
    environment:
      DATABASE_CL_CONNECTION_STRING: ${param:DATABASE_CL_CONNECTION_STRING}
      DATABASE_PE_CONNECTION_STRING: ${param:DATABASE_PE_CONNECTION_STRING}
      DYNAMODB_TABLE_APPOINTMENTS: ${param:DYNAMODB_TABLE_APPOINTMENTS}

    events:
      - httpApi: "GET /appointments"

  completeAppointment:
    handler: src/server/completeAppointment.handler
    environment:
      DYNAMODB_TABLE_APPOINTMENTS: ${param:DYNAMODB_TABLE_APPOINTMENTS}
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - CompleteAppointmentQueue
              - Arn

resources:
  - ${file(iac/dynamodb.yml)}
  - ${file(iac/pubsub-pe.yml)}
  - ${file(iac/pubsub-cl.yml)}
  - ${file(iac/event-bridge.yml)}

package:
  excludeDevDependencies: true
